import { Inter as FontSans } from "next/font/google"
import { cn } from '@inbaz3/primitives'


import { ThemeProvider } from "../components/theme-provider";
import { UserNav } from "../components/user-nav";
import { MainNav } from "../components/main-nav";

import './global.css';
import TeamSwitcher from "../components/team-switcher";
import { Search } from "../components/search";


const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata = {
  title: 'Welcome to nx-react-starter',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="border-b">
            <div className="flex h-16 items-center px-4">
              <TeamSwitcher />
              <MainNav className="mx-6" />
              <div className="ml-auto flex items-center space-x-4">
                <Search />
                <UserNav />
              </div>
            </div>
          </div>
          {/* <Header>
            <Header.Navigation>
              <NavigationMenuExample />
            </Header.Navigation>
            <ModeToggle />
          </Header> */}

          {children}
        </ThemeProvider>
      </body>
    </html >
  );
}
